
name: counter_app

on: 
 push: 
   branches: ["main"]

   jobs:
     build: 
    runs-on: ubuntu-latest

         steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Setup Node
           uses: actions/step-node@v3
            with:
             node-version: "16"
             - name: Install Dependencies
              run: npm ci
              - name: Build Project
               run: npm run build
              - name: Upload artifacts in order to deploy
                uses: actions/upload-artifact@v2
                with:
                  name: production-files
                   path: ./build

              deploy: 
              name: deploy
              runs-on: ubuntu-latest
              needs: build

              steps:
              - name: Download artifact
                uses: actions/download-artifact@v2
                with:
                 name: production-files
                 path: ./build
                
            -name: Deploy to github pages
             uses: peaceiris/actions-gh-pages@v3
             with:
               github_token: ${{secrets.GH_TOKEN}}
               publish_dir: ./build