
name: counter_app

on: 
 push:
   branches: ["main"]

   jobs:
     build: 
    runs-on: ubuntu-latest

         steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Setup Node
           uses: actions/step-node@v3
            with:
             node-version: "16"
          - name: Install Dependencies
            run: npm ci
          - name: Build Project
            run: npm run build
          deploy: 
           runs-on: ubuntu-latest
           needs: build
            environment:
              name: github-pages
              url: ${{ steps.deployment.outputs.page_url }}
            steps:
              - name: Deploy to Github pages
                id: deployment
              uses: action/deploy-pages@v1